2023-02-28 16:03:39,495 [DEBUG]  Available web server routes: 
/conversations/<conversation_id:path>/messages     POST                           add_message
/conversations/<conversation_id:path>/tracker/events POST                           append_events
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id:path>/execute      POST                           execute_action
/domain                                            GET                            get_domain
/socket.io                                         POST                           handle_request
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id:path>/predict      POST                           predict
/conversations/<conversation_id:path>/tracker/events PUT                            replace_events
/conversations/<conversation_id:path>/story        GET                            retrieve_story
/conversations/<conversation_id:path>/tracker      GET                            retrieve_tracker
/webhooks/socketio                                 GET                            socketio_webhook.health
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/conversations/<conversation_id:path>/trigger_intent POST                           trigger_intent
/model                                             DELETE                         unload_model
/version                                           GET                            version
2023-02-28 16:03:39,499 [INFO ]  Starting Rasa server on http://0.0.0.0:5005
2023-02-28 16:03:39,504 [DEBUG]  Using the default number of Sanic workers (1).
2023-02-28 16:03:39,975 [DEBUG]  Starting new HTTPS connection (1): api.segment.io:443
2023-02-28 16:03:41,248 [DEBUG]  https://api.segment.io:443 "POST /v1/track HTTP/1.1" 200 21
2023-02-28 16:03:41,292 [DEBUG]  Connected to InMemoryTrackerStore.
2023-02-28 16:03:41,293 [DEBUG]  Connected to lock store 'InMemoryLockStore'.
2023-02-28 16:03:41,294 [DEBUG]  Instantiated NLG to 'TemplatedNaturalLanguageGenerator'.
2023-02-28 16:03:41,295 [INFO ]  Loading model /app/models/20230228-160218-gentle-symphony.tar.gz...
2023-02-28 16:03:41,663 [DEBUG]  Extracted model to '/tmp/tmp0a9pewmz'.
2023-02-28 16:03:41,666 [DEBUG]  Node 'nlu_message_converter' loading 'NLUMessageConverter.load' and kwargs: '{}'.
2023-02-28 16:03:41,667 [DEBUG]  Node 'run_WhitespaceTokenizer0' loading 'WhitespaceTokenizer.load' and kwargs: '{}'.
2023-02-28 16:03:41,670 [DEBUG]  Node 'run_RegexFeaturizer1' loading 'RegexFeaturizer.load' and kwargs: '{}'.
2023-02-28 16:03:41,671 [DEBUG]  Resource 'train_RegexFeaturizer1' was requested for reading.
2023-02-28 16:03:41,672 [DEBUG]  Node 'run_LexicalSyntacticFeaturizer2' loading 'LexicalSyntacticFeaturizer.load' and kwargs: '{}'.
2023-02-28 16:03:41,672 [DEBUG]  Resource 'train_LexicalSyntacticFeaturizer2' was requested for reading.
2023-02-28 16:03:41,675 [DEBUG]  Node 'run_CountVectorsFeaturizer3' loading 'CountVectorsFeaturizer.load' and kwargs: '{}'.
2023-02-28 16:03:41,676 [DEBUG]  Resource 'train_CountVectorsFeaturizer3' was requested for reading.
2023-02-28 16:03:41,677 [DEBUG]  Node 'run_CountVectorsFeaturizer4' loading 'CountVectorsFeaturizer.load' and kwargs: '{}'.
2023-02-28 16:03:41,678 [DEBUG]  Resource 'train_CountVectorsFeaturizer4' was requested for reading.
2023-02-28 16:03:41,680 [DEBUG]  Node 'run_DIETClassifier5' loading 'DIETClassifier.load' and kwargs: '{}'.
2023-02-28 16:03:41,681 [DEBUG]  Resource 'train_DIETClassifier5' was requested for reading.
2023-02-28 16:03:41,682 [DEBUG]  Loading the model from /tmp/tmp89ds_w8_/train_DIETClassifier5/DIETClassifier.tf_model with finetune_mode=False...
2023-02-28 16:03:41,709 [DEBUG]  You specified 'DIET' to train entities, but no entities are present in the training data. Skipping training of entities.
2023-02-28 16:03:41,732 [DEBUG]  Following metrics will be logged during training: 
2023-02-28 16:03:41,733 [DEBUG]    t_loss (total loss)
2023-02-28 16:03:41,734 [DEBUG]    i_acc (intent acc)
2023-02-28 16:03:41,735 [DEBUG]    i_loss (intent loss)
2023-02-28 16:03:49,382 [DEBUG]  Finished loading the model.
2023-02-28 16:03:49,383 [DEBUG]  Node 'run_EntitySynonymMapper6' loading 'EntitySynonymMapper.load' and kwargs: '{}'.
2023-02-28 16:03:49,383 [DEBUG]  Resource 'train_EntitySynonymMapper6' was requested for reading.
2023-02-28 16:03:49,384 [DEBUG]  Failed to load ABCMeta from model storage. Resource 'train_EntitySynonymMapper6' doesn't exist.
2023-02-28 16:03:49,385 [DEBUG]  Node 'run_ResponseSelector7' loading 'ResponseSelector.load' and kwargs: '{}'.
2023-02-28 16:03:49,386 [DEBUG]  Resource 'train_ResponseSelector7' was requested for reading.
2023-02-28 16:03:49,387 [DEBUG]  Failed to load ABCMeta from model storage. Resource 'train_ResponseSelector7' doesn't exist.
2023-02-28 16:03:49,388 [DEBUG]  Resource 'train_ResponseSelector7' was requested for reading.
2023-02-28 16:03:49,389 [DEBUG]  Failed to load ResponseSelector from model storage. Resource 'train_ResponseSelector7' doesn't exist.
2023-02-28 16:03:49,390 [DEBUG]  Node 'run_FallbackClassifier8' loading 'FallbackClassifier.load' and kwargs: '{}'.
2023-02-28 16:03:49,390 [DEBUG]  Node 'run_RegexMessageHandler' loading 'RegexMessageHandler.load' and kwargs: '{}'.
2023-02-28 16:03:49,391 [DEBUG]  Node 'domain_provider' loading 'DomainProvider.load' and kwargs: '{}'.
2023-02-28 16:03:49,391 [DEBUG]  Resource 'domain_provider' was requested for reading.
2023-02-28 16:03:49,425 [DEBUG]  Node 'run_MemoizationPolicy0' loading 'MemoizationPolicy.load' and kwargs: '{}'.
2023-02-28 16:03:49,426 [DEBUG]  Resource 'train_MemoizationPolicy0' was requested for reading.
2023-02-28 16:03:49,427 [DEBUG]  Node 'run_RulePolicy1' loading 'RulePolicy.load' and kwargs: '{}'.
2023-02-28 16:03:49,427 [DEBUG]  Resource 'train_RulePolicy1' was requested for reading.
2023-02-28 16:03:49,429 [DEBUG]  Node 'run_UnexpecTEDIntentPolicy2' loading 'UnexpecTEDIntentPolicy.load' and kwargs: '{}'.
2023-02-28 16:03:49,429 [DEBUG]  Resource 'train_UnexpecTEDIntentPolicy2' was requested for reading.
2023-02-28 16:03:49,431 [DEBUG]  Loading the model from /tmp/tmp89ds_w8_/train_UnexpecTEDIntentPolicy2/unexpected_intent_policy.tf_model with finetune_mode=False...
2023-02-28 16:03:56,594 [DEBUG]  Finished loading the model.
2023-02-28 16:03:56,595 [WARNI]  The UnexpecTED Intent Policy is currently experimental and might change or be removed in the future ðŸ”¬ Please share your feedback on it in the forum (https://forum.rasa.com) to help us make this feature ready for production.
2023-02-28 16:03:56,596 [DEBUG]  Node 'run_TEDPolicy3' loading 'TEDPolicy.load' and kwargs: '{}'.
2023-02-28 16:03:56,596 [DEBUG]  Resource 'train_TEDPolicy3' was requested for reading.
2023-02-28 16:03:56,599 [DEBUG]  Loading the model from /tmp/tmp89ds_w8_/train_TEDPolicy3/ted_policy.tf_model with finetune_mode=False...
2023-02-28 16:04:03,172 [DEBUG]  Finished loading the model.
2023-02-28 16:04:03,173 [DEBUG]  Node 'rule_only_data_provider' loading 'RuleOnlyDataProvider.load' and kwargs: '{}'.
2023-02-28 16:04:03,173 [DEBUG]  Resource 'train_RulePolicy1' was requested for reading.
2023-02-28 16:04:03,174 [DEBUG]  Node 'select_prediction' loading 'DefaultPolicyPredictionEnsemble.load' and kwargs: '{}'.
2023-02-28 16:04:03,181 [INFO ]  Rasa server is up and running.
2023-02-28 16:04:03,184 [INFO ]  Enabling coroutine debugging. Loop id 94853873539120.
2023-02-28 16:04:04,327 [DEBUG]  User jJdQCO8VcP7176OGAAAB connected to socketIO endpoint.
2023-02-28 16:04:04,347 [DEBUG]  User jJdQCO8VcP7176OGAAAB connected to socketIO endpoint.
2023-02-28 16:05:21,420 [DEBUG]  User jJdQCO8VcP7176OGAAAB disconnected from socketIO endpoint.
2023-02-28 16:05:21,421 [ERROR]  Exception occurred while handling uri: 'ws://localhost:5005/socket.io/?EIO=4&transport=websocket&sid=B1CUGLT9GGwIcvbvAAAA'
Traceback (most recent call last):
  File "handle_request", line 124, in handle_request
sanic.exceptions.ServerError: Invalid response type None (need HTTPResponse)
2023-02-28 16:05:23,031 [DEBUG]  User jbBI0Hay9hic7TkuAAAD connected to socketIO endpoint.
2023-02-28 16:05:23,056 [DEBUG]  User jbBI0Hay9hic7TkuAAAD connected to socketIO endpoint.
2023-02-28 16:05:26,276 [DEBUG]  Issuing ticket for conversation '9f5344854afa4e39be8eb2c115c6aa1f'.
2023-02-28 16:05:26,277 [DEBUG]  Acquiring lock for conversation '9f5344854afa4e39be8eb2c115c6aa1f'.
2023-02-28 16:05:26,278 [DEBUG]  Acquired lock for conversation '9f5344854afa4e39be8eb2c115c6aa1f'.
2023-02-28 16:05:26,279 [DEBUG]  Could not find tracker for conversation ID '9f5344854afa4e39be8eb2c115c6aa1f'.
2023-02-28 16:05:26,280 [DEBUG]  Starting a new session for conversation ID '9f5344854afa4e39be8eb2c115c6aa1f'.
2023-02-28 16:05:26,282 [DEBUG]  Policy prediction ended with events '[]'.
2023-02-28 16:05:26,282 [DEBUG]  Action 'action_session_start' ended with events '[<rasa.shared.core.events.SessionStarted object at 0x7f2e364da2c0>, ActionExecuted(action: action_listen, policy: None, confidence: None)]'.
2023-02-28 16:05:26,283 [DEBUG]  Current slot values: 
	session_started_metadata: None
2023-02-28 16:05:26,284 [DEBUG]  Running graph with inputs: {'__message__': [<rasa.core.channels.channel.UserMessage object at 0x7f2e364d9990>]}, targets: ['run_RegexMessageHandler'] and ExecutionContext(model_id='484513f690be4fc4aa9464558fe57f9f', should_add_diagnostic_data=False, is_finetuning=False, node_name=None).
2023-02-28 16:05:26,286 [DEBUG]  Node 'nlu_message_converter' running 'NLUMessageConverter.convert_user_message'.
2023-02-28 16:05:26,287 [DEBUG]  Node 'run_WhitespaceTokenizer0' running 'WhitespaceTokenizer.process'.
2023-02-28 16:05:26,290 [DEBUG]  Node 'run_RegexFeaturizer1' running 'RegexFeaturizer.process'.
2023-02-28 16:05:26,292 [DEBUG]  Node 'run_LexicalSyntacticFeaturizer2' running 'LexicalSyntacticFeaturizer.process'.
2023-02-28 16:05:26,293 [DEBUG]  Node 'run_CountVectorsFeaturizer3' running 'CountVectorsFeaturizer.process'.
2023-02-28 16:05:26,295 [DEBUG]  Node 'run_CountVectorsFeaturizer4' running 'CountVectorsFeaturizer.process'.
2023-02-28 16:05:26,296 [DEBUG]  Node 'run_DIETClassifier5' running 'DIETClassifier.process'.
2023-02-28 16:05:26,456 [DEBUG]  Node 'run_EntitySynonymMapper6' running 'EntitySynonymMapper.process'.
2023-02-28 16:05:26,457 [DEBUG]  Node 'run_ResponseSelector7' running 'ResponseSelector.process'.
2023-02-28 16:05:26,457 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2023-02-28 16:05:26,458 [DEBUG]  Adding following selector key to message property: default
2023-02-28 16:05:26,459 [DEBUG]  Node 'run_FallbackClassifier8' running 'FallbackClassifier.process'.
2023-02-28 16:05:26,459 [DEBUG]  Node 'domain_provider' running 'DomainProvider.provide_inference'.
2023-02-28 16:05:26,460 [DEBUG]  Node 'run_RegexMessageHandler' running 'RegexMessageHandler.process'.
2023-02-28 16:05:26,461 [DEBUG]  Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9999158382415771}' and entities '[]'
2023-02-28 16:05:26,462 [DEBUG]  Logged UserUtterance - tracker now has 4 events.
2023-02-28 16:05:26,463 [DEBUG]  Validating extracted slots: 
2023-02-28 16:05:26,463 [DEBUG]  Default action 'action_extract_slots' was executed, resulting in 0 events: 
2023-02-28 16:05:26,464 [DEBUG]  Running graph with inputs: {'__tracker__': <rasa.shared.core.trackers.DialogueStateTracker object at 0x7f2e364d98d0>}, targets: ['select_prediction'] and ExecutionContext(model_id='484513f690be4fc4aa9464558fe57f9f', should_add_diagnostic_data=False, is_finetuning=False, node_name=None).
2023-02-28 16:05:26,465 [DEBUG]  Node 'rule_only_data_provider' running 'RuleOnlyDataProvider.provide'.
2023-02-28 16:05:26,466 [DEBUG]  Node 'domain_provider' running 'DomainProvider.provide_inference'.
2023-02-28 16:05:26,469 [DEBUG]  Node 'run_MemoizationPolicy0' running 'MemoizationPolicy.predict_action_probabilities'.
2023-02-28 16:05:26,471 [DEBUG]  Current tracker state:
[state 1] user intent: greet | previous action name: action_listen
2023-02-28 16:05:26,472 [DEBUG]  There is a memorised next action 'utter_greet'
2023-02-28 16:05:26,473 [DEBUG]  Node 'run_RulePolicy1' running 'RulePolicy.predict_action_probabilities'.
2023-02-28 16:05:26,474 [DEBUG]  Current tracker state:
[state 1] user text: hi | previous action name: action_listen
2023-02-28 16:05:26,475 [DEBUG]  There is no applicable rule.
2023-02-28 16:05:26,476 [DEBUG]  Current tracker state:
[state 1] user intent: greet | previous action name: action_listen
2023-02-28 16:05:26,476 [DEBUG]  There is no applicable rule.
2023-02-28 16:05:26,477 [DEBUG]  Node 'run_TEDPolicy3' running 'TEDPolicy.predict_action_probabilities'.
2023-02-28 16:05:26,483 [DEBUG]  TED predicted 'utter_greet' based on user intent.
2023-02-28 16:05:26,486 [DEBUG]  Node 'run_UnexpecTEDIntentPolicy2' running 'UnexpecTEDIntentPolicy.predict_action_probabilities'.
2023-02-28 16:05:26,720 [DEBUG]  Querying for intent `greet`.
2023-02-28 16:05:26,720 [DEBUG]  Score for intent `greet` is `0.6661381721496582`, while threshold is `0.6186959743499756`.
2023-02-28 16:05:26,721 [DEBUG]  Top 5 intents (in ascending order) that are likely here are: `[('goodbye', 0.45221004), ('network_provider', 0.46965665), ('pocket_limit', 0.48430264), ('Sepcific_services', 0.585783), ('greet', 0.6661382)]`.
2023-02-28 16:05:26,722 [DEBUG]  Node 'select_prediction' running 'DefaultPolicyPredictionEnsemble.combine_predictions_from_kwargs'.
2023-02-28 16:05:26,723 [DEBUG]  Made prediction using user intent.
2023-02-28 16:05:26,723 [DEBUG]  Added `DefinePrevUserUtteredFeaturization(False)` event.
2023-02-28 16:05:26,724 [DEBUG]  Predicted next action using MemoizationPolicy.
2023-02-28 16:05:26,725 [DEBUG]  Predicted next action 'utter_greet' with confidence 1.00.
2023-02-28 16:05:26,726 [DEBUG]  Policy prediction ended with events '[<rasa.shared.core.events.DefinePrevUserUtteredFeaturization object at 0x7f2e364da4a0>]'.
2023-02-28 16:05:26,727 [DEBUG]  Action 'utter_greet' ended with events '[BotUttered('- Hello, my friend.
- I'm your virtual Assistant.
', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {"utter_action": "utter_greet"}, 1677600326.7267387)]'.
2023-02-28 16:05:26,733 [DEBUG]  Running graph with inputs: {'__tracker__': <rasa.shared.core.trackers.DialogueStateTracker object at 0x7f2e364d98d0>}, targets: ['select_prediction'] and ExecutionContext(model_id='484513f690be4fc4aa9464558fe57f9f', should_add_diagnostic_data=False, is_finetuning=False, node_name=None).
2023-02-28 16:05:26,735 [DEBUG]  Node 'rule_only_data_provider' running 'RuleOnlyDataProvider.provide'.
2023-02-28 16:05:26,737 [DEBUG]  Node 'domain_provider' running 'DomainProvider.provide_inference'.
2023-02-28 16:05:26,738 [DEBUG]  Node 'run_MemoizationPolicy0' running 'MemoizationPolicy.predict_action_probabilities'.
2023-02-28 16:05:26,739 [DEBUG]  Current tracker state:
[state 1] user intent: greet | previous action name: action_listen
[state 2] user intent: greet | previous action name: utter_greet
2023-02-28 16:05:26,740 [DEBUG]  There is a memorised next action 'action_listen'
2023-02-28 16:05:26,741 [DEBUG]  Node 'run_RulePolicy1' running 'RulePolicy.predict_action_probabilities'.
2023-02-28 16:05:26,741 [DEBUG]  Current tracker state:
[state 1] user intent: greet | previous action name: action_listen
[state 2] user intent: greet | previous action name: utter_greet
2023-02-28 16:05:26,742 [DEBUG]  There is no applicable rule.
2023-02-28 16:05:26,743 [DEBUG]  Node 'run_TEDPolicy3' running 'TEDPolicy.predict_action_probabilities'.
2023-02-28 16:05:26,749 [DEBUG]  TED predicted 'action_listen' based on user intent.
2023-02-28 16:05:26,751 [DEBUG]  Node 'run_UnexpecTEDIntentPolicy2' running 'UnexpecTEDIntentPolicy.predict_action_probabilities'.
2023-02-28 16:05:26,751 [DEBUG]  Skipping predictions for UnexpecTEDIntentPolicy as either there is no event of type `UserUttered`, event's intent is new and not in domain or there is an event of type `ActionExecuted` after the last `UserUttered`.
2023-02-28 16:05:26,752 [DEBUG]  Node 'select_prediction' running 'DefaultPolicyPredictionEnsemble.combine_predictions_from_kwargs'.
2023-02-28 16:05:26,753 [DEBUG]  Predicted next action using MemoizationPolicy.
2023-02-28 16:05:26,754 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2023-02-28 16:05:26,755 [DEBUG]  Policy prediction ended with events '[]'.
2023-02-28 16:05:26,755 [DEBUG]  Action 'action_listen' ended with events '[]'.
2023-02-28 16:05:26,756 [DEBUG]  Deleted lock for conversation '9f5344854afa4e39be8eb2c115c6aa1f'.
2023-02-28 16:05:30,163 [DEBUG]  User jbBI0Hay9hic7TkuAAAD disconnected from socketIO endpoint.
2023-02-28 16:05:30,165 [ERROR]  Exception occurred while handling uri: 'ws://localhost:5005/socket.io/?EIO=4&transport=websocket&sid=qVJyxFp-S13g6XmAAAAC'
Traceback (most recent call last):
  File "handle_request", line 124, in handle_request
sanic.exceptions.ServerError: Invalid response type None (need HTTPResponse)
2023-02-28 16:05:34,470 [ERROR]  Task was destroyed but it is pending!
source_traceback: Object created at (most recent call last):
  File "/opt/venv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.10/site-packages/rasa/__main__.py", line 126, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/opt/venv/lib/python3.10/site-packages/rasa/cli/run.py", line 93, in run
    rasa.run(**vars(args))
  File "/opt/venv/lib/python3.10/site-packages/rasa/api.py", line 56, in run
    rasa.core.run.serve_application(
  File "/opt/venv/lib/python3.10/site-packages/rasa/core/run.py", line 229, in serve_application
    app.run(
  File "/opt/venv/lib/python3.10/site-packages/sanic/app.py", line 1204, in run
    serve_single(server_settings)
  File "/opt/venv/lib/python3.10/site-packages/sanic/server/runners.py", line 206, in serve_single
    serve(**server_settings)
  File "/opt/venv/lib/python3.10/site-packages/sanic/server/runners.py", line 155, in serve
    loop.run_forever()
  File "connection_task", line 15, in connection_task
    from sanic.http import Http, Stage
  File "/opt/venv/lib/python3.10/site-packages/sanic/http.py", line 146, in http1
    await self.protocol.request_handler(self.request)
  File "handle_request", line 83, in handle_request
    )
  File "/opt/venv/lib/python3.10/site-packages/engineio/asyncio_server.py", line 258, in handle_request
    r = await self._handle_connect(environ, transport,
  File "/opt/venv/lib/python3.10/site-packages/engineio/asyncio_server.py", line 396, in _handle_connect
    self.start_background_task(self._service_task)
  File "/opt/venv/lib/python3.10/site-packages/engineio/asyncio_server.py", line 332, in start_background_task
    return asyncio.ensure_future(target(*args, **kwargs))
  File "/usr/lib/python3.10/asyncio/tasks.py", line 615, in ensure_future
    return _ensure_future(coro_or_future, loop=loop)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 636, in _ensure_future
    return loop.create_task(coro_or_future)
task: <Task pending name='Task-7' coro=<AsyncServer._service_task() running at /opt/venv/lib/python3.10/site-packages/engineio/asyncio_server.py:498> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/tasks.py:600> created at /usr/lib/python3.10/asyncio/tasks.py:636>
2023-02-28 16:05:34,473 [ERROR]  Task was destroyed but it is pending!
source_traceback: Object created at (most recent call last):
  File "/opt/venv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.10/site-packages/rasa/__main__.py", line 126, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/opt/venv/lib/python3.10/site-packages/rasa/cli/run.py", line 93, in run
    rasa.run(**vars(args))
  File "/opt/venv/lib/python3.10/site-packages/rasa/api.py", line 56, in run
    rasa.core.run.serve_application(
  File "/opt/venv/lib/python3.10/site-packages/rasa/core/run.py", line 229, in serve_application
    app.run(
  File "/opt/venv/lib/python3.10/site-packages/sanic/app.py", line 1204, in run
    serve_single(server_settings)
  File "/opt/venv/lib/python3.10/site-packages/sanic/server/runners.py", line 206, in serve_single
    serve(**server_settings)
  File "/opt/venv/lib/python3.10/site-packages/sanic/server/runners.py", line 155, in serve
    loop.run_forever()
  File "connection_task", line 15, in connection_task
    from sanic.http import Http, Stage
  File "/opt/venv/lib/python3.10/site-packages/sanic/http.py", line 146, in http1
    await self.protocol.request_handler(self.request)
  File "handle_request", line 83, in handle_request
    )
  File "/opt/venv/lib/python3.10/site-packages/engineio/asyncio_server.py", line 271, in handle_request
    packets = await socket.handle_get_request(environ)
  File "/opt/venv/lib/python3.10/site-packages/engineio/asyncio_socket.py", line 89, in handle_get_request
    return await getattr(self, '_upgrade_' + transport)(environ)
  File "/opt/venv/lib/python3.10/site-packages/engineio/asyncio_socket.py", line 142, in _upgrade_websocket
    return await ws(environ)
  File "/opt/venv/lib/python3.10/site-packages/engineio/async_drivers/sanic.py", line 125, in __call__
    await self.handler(self)
  File "/opt/venv/lib/python3.10/site-packages/engineio/asyncio_socket.py", line 238, in _websocket_handler
    await self.receive(pkt)
  File "/opt/venv/lib/python3.10/site-packages/engineio/asyncio_socket.py", line 42, in receive
    self.schedule_ping()
  File "/opt/venv/lib/python3.10/site-packages/engineio/asyncio_socket.py", line 132, in schedule_ping
    self.server.start_background_task(send_ping)
  File "/opt/venv/lib/python3.10/site-packages/engineio/asyncio_server.py", line 332, in start_background_task
    return asyncio.ensure_future(target(*args, **kwargs))
  File "/usr/lib/python3.10/asyncio/tasks.py", line 615, in ensure_future
    return _ensure_future(coro_or_future, loop=loop)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 636, in _ensure_future
    return loop.create_task(coro_or_future)
task: <Task pending name='Task-45' coro=<AsyncSocket.schedule_ping.<locals>.send_ping() running at /opt/venv/lib/python3.10/site-packages/engineio/asyncio_socket.py:127> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/tasks.py:600> created at /usr/lib/python3.10/asyncio/tasks.py:636>
2023-02-28 16:05:34,473 [ERROR]  Task was destroyed but it is pending!
source_traceback: Object created at (most recent call last):
  File "/opt/venv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.10/site-packages/rasa/__main__.py", line 126, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/opt/venv/lib/python3.10/site-packages/rasa/cli/run.py", line 93, in run
    rasa.run(**vars(args))
  File "/opt/venv/lib/python3.10/site-packages/rasa/api.py", line 56, in run
    rasa.core.run.serve_application(
  File "/opt/venv/lib/python3.10/site-packages/rasa/core/run.py", line 229, in serve_application
    app.run(
  File "/opt/venv/lib/python3.10/site-packages/sanic/app.py", line 1204, in run
    serve_single(server_settings)
  File "/opt/venv/lib/python3.10/site-packages/sanic/server/runners.py", line 206, in serve_single
    serve(**server_settings)
  File "/opt/venv/lib/python3.10/site-packages/sanic/server/runners.py", line 155, in serve
    loop.run_forever()
  File "connection_task", line 15, in connection_task
    from sanic.http import Http, Stage
  File "/opt/venv/lib/python3.10/site-packages/sanic/http.py", line 146, in http1
    await self.protocol.request_handler(self.request)
  File "handle_request", line 83, in handle_request
    )
  File "/opt/venv/lib/python3.10/site-packages/engineio/asyncio_server.py", line 258, in handle_request
    r = await self._handle_connect(environ, transport,
  File "/opt/venv/lib/python3.10/site-packages/engineio/asyncio_server.py", line 408, in _handle_connect
    s.schedule_ping()
  File "/opt/venv/lib/python3.10/site-packages/engineio/asyncio_socket.py", line 132, in schedule_ping
    self.server.start_background_task(send_ping)
  File "/opt/venv/lib/python3.10/site-packages/engineio/asyncio_server.py", line 332, in start_background_task
    return asyncio.ensure_future(target(*args, **kwargs))
  File "/usr/lib/python3.10/asyncio/tasks.py", line 615, in ensure_future
    return _ensure_future(coro_or_future, loop=loop)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 636, in _ensure_future
    return loop.create_task(coro_or_future)
task: <Task pending name='Task-50' coro=<AsyncSocket.schedule_ping.<locals>.send_ping() running at /opt/venv/lib/python3.10/site-packages/engineio/asyncio_socket.py:127> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/tasks.py:600> created at /usr/lib/python3.10/asyncio/tasks.py:636>
